# AIR CON COMMAND
rest_command:
  aircon_control:
    url: 'http://192.168.1.106:2025/setAircon?json={{ command }}'
    method: 'GET'

# AIR CON TEMPERATURE DIAL
input_number:
  aircon_temperature:
    name: Aircon Temperature
    initial: 23
    min: 16
    max: 32
    step: 1
  aircon_countdown_timer:
    name: Aircon Countdown Timer
    initial: 0
    min: 0
    max: 300
    step: 15
    
 # AIR CON RUN MODE
input_select:
    aircon_run_mode:
        name: Aircon Run Mode
        options:
          - cool
          - heat
          - vent
          - dry
        initial: cool  
        icon: mdi:air-conditioner

script:
  aircon_turn_off:
    sequence:
    - data:
        command: '{"ac1":{"info":{"state":"off"}}}'
      service: rest_command.aircon_on_off
  aircon_turn_on:
    sequence:
    - data:
        command: '{"ac1":{"info":{"state":"on"}}}'
      service: rest_command.aircon_on_off
      
  #Warm the master bedroom for 60 minutes
  aircon_warm_master:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 18
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: heat
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_on
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_off
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    - delay:
        seconds: 10
    - data:
        entity_id: input_number.aircon_countdown_timer
        value: 60
      service: input_number.set_value
    alias: Aircon Warm Master
    
  #Run the fan in the master bedroom for 60 minutes
  aircon_fan_master:
    sequence:
    - data:
        entity_id: input_select.aircon_run_mode
        option: vent
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_on
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_off
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    - delay:
        seconds: 10
    - data:
        entity_id: input_number.aircon_countdown_timer
        value: 60
      service: input_number.set_value
    alias: Aircon Fan Master
    
  #Run the aircon in the central living area
  aircon_cool_central_living:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 19
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: cool
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_on
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_off
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Aircon Cool Central Living

  #Run the aircon in the theatre room
  aircon_cool_theatre:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 23
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: cool
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_on
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Aircon Cool Theatre

  #Run the aircon in cool mode
  aircon_cool:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 20
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: cool
      service: input_select.select_option
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Aircon On
    
  #Run the aircon in heat mode
  aircon_heat:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 24
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: heat
      service: input_select.select_option
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Heater On

automation:
  - alias: Aircon - Adjust Temperature From Slider
    trigger: 
      platform: state
      entity_id: input_number.aircon_temperature
    action:
      - service: rest_command.aircon_control
        data_template:
          command: '{"ac1":{"info":{"setTemp":{{ states.input_number.aircon_temperature.state | int }}}}}'
            
  - alias: Aircon - Adjust Temperature From Sensor
    trigger: 
      platform: state
      entity_id: sensor.aircon_temperature
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.aircon_temperature
          value: "{{ states.sensor.aircon_temperature.state }}"
          
  - alias: Aircon - Adjust Countdown Timer From Slider
    trigger: 
      platform: state
      entity_id: input_number.aircon_countdown_timer
    action:
      - service: rest_command.aircon_control
        data_template:
          command: '{"ac1":{"info":{"countDownToOff":{{ states.input_number.aircon_countdown_timer.state | int }}}}}'
            
  - alias: Aircon - Adjust Countdown Timer From Sensor
    trigger: 
      platform: state
      entity_id: sensor.aircon_countdown_timer
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.aircon_countdown_timer
          value: "{{ states.sensor.aircon_countdown_timer.state }}"

  - alias: Aircon - Set Run Mode From Selector
    trigger: 
      platform: state
      entity_id: input_select.aircon_run_mode
    action:
      - service: rest_command.aircon_control
        data_template:
          command: '{"ac1":{"info":{"mode":{{ states.input_select.aircon_run_mode.state }}}}}'

  - alias: Aircon - Set Run Mode From Sensor
    trigger: 
      platform: state
      entity_id: sensor.aircon_run_mode
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.aircon_run_mode
          option: "{{ states.sensor.aircon_run_mode.state }}"

  - alias: Morning Warmth
    trigger:
      - platform: time
        at: '06:00:00'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: numeric_state
        entity_id: weather.bom_perth
        below: '8'
        value_template: '{{ state.attributes.temperature }}'
    action:
      - service: script.aircon_warm_master

  - alias: Solar Cooling
    trigger:
      platform: time_pattern
      minutes: "/1" #This will match every 1 minutes
    condition:
      - condition: template
        value_template: '{{ (states.sensor.lumi_lumi_sens_02281d85_1_1026.state | float) > 25.0 }}' #if the inside temperature is > 25 degrees  
      - condition: template
        value_template: '{{ (states.sensor.sems_output_power.state | float) > 2000.0 }}' #if the solar panels are running well
      - condition: state
        entity_id: 'alarm_control_panel.alarm_com'
        state: 'armed_away' #nobody is home
      - condition: state
        entity_id: 'switch.aircon_on_off'
        state: 'off' #don't run the script if the aircon is already on, as it will restart the countdown timer
    action:
      - service: script.aircon_cool_central_living #run the aircon in the central living area
      - delay: #wait until it's up and running
          seconds: 30 
      - service: input_number.set_value #stop the aircon after 15 minutes
        data_template: 
          entity_id: input_number.aircon_countdown_timer
          value: 15

#NOTE: This automation probably won't work correctly until I get a more reliable means of prescence detection in the master bedroom
  - alias: Auto Bedroom Fan 
    trigger:
      - platform: state
        entity_id: sensor.motion_sensor_master_bedroom
        to: 'Active' #motion was detected in the master bedroom
    condition:
      - condition: time
        after: '21:30:00' #it's after 9.30pm
      - condition: template
        value_template: '{{ (states.sensor.lumi_lumi_sens_2fa41804_temperature.state | float) > 25.0 }}' #the bedroom temperature is > 25 degrees  
      - condition: state
        entity_id: 'switch.aircon_on_off'
        state: 'off' #don't run the script if the fan is already on, as it will restart the countdown timer
    action:
      - service: script.aircon_fan_master #run the fan in the master bedroom


sensor:
  # Aircon State Sensor
  - platform: rest
    resource: http://192.168.1.106:2025/getSystemData
    name: aircon_sensor
    value_template: '{{ value_json.aircons.ac1.info.state }}'
    scan_interval: 5
    json_attributes:
      - aircons

  - platform: template
    sensors:
      aircon_zone_living: #aircon zone z01
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z01"]["state"] }}'
      aircon_zone_theatre: #aircon zone z02
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z02"]["state"] }}'
      aircon_zone_master: #aircon zone z03
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z03"]["state"] }}'
      aircon_zone_bed23: #aircon zone z04
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z04"]["state"] }}'
      aircon_temperature: #aircon current temperature
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["info"]["setTemp"] }}'
        device_class: temperature
        unit_of_measurement: 'Â°C'
      aircon_run_mode: #aircon fan mode sensor
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["info"]["mode"] }}'
      aircon_countdown_timer: #minutes before turning off
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["info"]["countDownToOff"] }}'

switch:
  - platform: template
    switches:
    
      aircon_on_off: #overall aircon control
        value_template: "{{ is_state('sensor.aircon_sensor', 'on') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            #when turning on, set the countdown timer to 0
            command: '{"ac1":{"info":{"state":"on","countDownToOff": 0}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"info":{"state":"off"}}}'
            
      aircon_zone_living: #zone z01
        value_template: "{{ is_state('sensor.aircon_zone_living', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z01":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z01":{"state":"close"}}}}'
            
      aircon_zone_theatre: #zone z02
        value_template: "{{ is_state('sensor.aircon_zone_theatre', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z02":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z02":{"state":"close"}}}}'      
            
      aircon_zone_master: #zone z03
        value_template: "{{ is_state('sensor.aircon_zone_master', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z03":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z03":{"state":"close"}}}}'  
      
      aircon_zone_bed23: #zone z04
        value_template: "{{ is_state('sensor.aircon_zone_bed23', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z04":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z04":{"state":"close"}}}}'

group:
  aircon_vents:
    name: Aircon Vents
    entities:
      - switch.aircon_zone_bed23
      - switch.aircon_zone_living
      - switch.aircon_zone_master
      - switch.aircon_zone_theatre
    